fid=fopen('F:\资料\脑部PET\hoffman 脑膜\Hoffman64x64x12_32bitReal_littleEndian.IMG','r');
hoffman=fread(fid,'float');
fclose(fid);
hoffman=reshape(hoffman,64,64,12);
figure;imshow(hoffman(:,:,6),[0,100]);
pathTemp2=strcat('C:\Users\twj2417\Desktop\hoffman\runG.sh');
fid3=fopen(pathTemp2,'w');
fprintf(fid3,'%s\n','#!/bin/bash/');
for i=1:64
    Length=floor(sqrt(31.5^2-(i-32.5)^2));
    if Length>0
        image=hoffman(33-Length:32+Length,i,:);
        %%  写二进制数据
        pathTemp=strcat('C:\Users\twj2417\Desktop\hoffman\',num2str(i),'\hoffman_',num2str(i),'.s');
        fid1=fopen(pathTemp,'w');
        fwrite(fid1,image,'float');
        fclose(fid1);
        %%  写二进制头文件
        pathTemp1=strcat('C:\Users\twj2417\Desktop\hoffman\',num2str(i),'\hoffman_',num2str(i),'.h33');
        fid2=fopen(pathTemp1,'w');
        fprintf(fid2,'%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n','!INTERFILE :=',...
            ' !imaging modality := nucmed',...
            '!originating system := greetings',...
            '!version of keys := 3.3',...
            'date of keys := 1996:09:24',...
            'conversion program := (X)MedCon',...
            'program author := Erik Nolf',...
            'program version := 0.7.4',...
            'program date := 2002:02:18',...
            '!GENERAL DATA :=',...
            '!data offset in bytes := 0 ',...
            strcat('!name of data file := hoffman_',num2str(i),'.s'),...
            'patient name := hf',...
            '!patient ID := 271097',...
            'patient dob := 0000:00:00',...
            'patient sex := Unknown',...
            '!study ID := brain',...
            'exam type := pet   study',...
            'data compression := none',...
            'data encode := none',...
            '!GENERAL IMAGE DATA :=',...
            '!type of data := Tomographic',...
            '!total number of images := 12',...
            'study date := 1997:11:28',...
            'study time := 00:00:00',...
            'imagedata byte order := LITTLEENDIAN',...
            'number of energy windows := 1',...
            'energy window [1] :=',...
            'energy window lower level [1] :=',...
            'energy window upper level [1] :=',...
            'flood corrected := N',...
            'decay corrected := N',...
            '!SPECT STUDY (general) :=',...
            'number of detector heads := 1',...
            '!number of images/energy window := 2',...
            '!process status := Reconstructed',...
            strcat('!matrix size [1] :=', num2str(2*Length)),...
            '!matrix size [2] := 1',...
            '!number format := float',...
            '!number of bytes per pixel := 4',...
            'scaling factor (mm/pixel) [1] := +3.0000000e+00',...
            'scaling factor (mm/pixel) [2] := +3.0000000e+00',...
            '!number of projections := 12',...
            '!extent of rotation := ',...
            '!time per projection (sec) := 0',...
            'study duration (sec) := 0',...
            '!maximum pixel count := +2.000000e+05',...
            'patient orientation := head_in',...
            'patient rotation := supine',...
            '!SPECT STUDY (reconstructed data) :=',...
            'method of reconstruction := Unknown',...
            '!number of slices := 12',...
            'number of reference frame := 0',...
            'slice orientation := Transverse',...
            'slice thickness (pixels) := +1.500000e+01',...
            'centre-centre slice separation (pixels) := +1.500000e+01',...
            'filter name := Unknown',...
            'filter parameters := Cutoff',...
            'method of attenuation correction := measured',...
            'scatter corrected := N',...
            'oblique reconstruction := N',...
            '!END OF INTERFILE :=');
        fclose(fid2);
        %%  写mac文件
        pathTemp4=strcat('C:\Users\twj2417\Desktop\hoffman\',num2str(i),'\hoffman_',num2str(i),'new.mac');
        fid5=fopen(pathTemp4,'w');
        fprintf(fid5,'%s\n','/vis/disable');
        fprintf(fid5,'%s\n','#/vis/viewer/set/viewpointThetaPhi   60 60');
        fprintf(fid5,'%s\n','#/vis/viewer/zoom                    6.0');
        fprintf(fid5,'%s\n','#/vis/drawVolume');
        fprintf(fid5,'%s\n','#/tracking/storeTrajectory           1');
        fprintf(fid5,'%s\n','#/vis/scene/add/trajectories ');
        fprintf(fid5,'%s\n','#/vis/scene/endOfEventAction         accumulate ');
        fprintf(fid5,'%s\n','/control/execute                    Verbose.mac ');
        fprintf(fid5,'%s\n','/gate/geometry/setMaterialDatabase    GateMaterials.db ');
        fprintf(fid5,'%s\n','#WORLD');
        fprintf(fid5,'%s\n','/gate/world/geometry/setXLength 400. cm');
        fprintf(fid5,'%s\n','/gate/world/geometry/setYLength 400. cm');
        fprintf(fid5,'%s\n','/gate/world/geometry/setZLength 400. cm ');
        fprintf(fid5,'%s\n','#SYSTEM ');
        fprintf(fid5,'%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n','/gate/world/daughters/name ecat',...
            '/gate/world/daughters/insert cylinder',...
            '/gate/ecat/setMaterial Air',...
            '/gate/ecat/geometry/setRmax 13 cm',...
            '/gate/ecat/geometry/setRmin 9.7 cm',...
            '/gate/ecat/geometry/setHeight 11 cm',...
            '#     B L O C K',...
            '/gate/ecat/daughters/name block',...
            '/gate/ecat/daughters/insert box',...
            '/gate/block/placement/setTranslation 100.5 0.0 0.0 mm',...
            '/gate/block/geometry/setXLength 7.0 mm',...
            '/gate/block/geometry/setYLength 38.4 mm',...
            '/gate/block/geometry/setZLength 100.8 mm',...
            '/gate/block/setMaterial BaSO4',...
            '#	C R Y S T A L',...
            '/gate/block/daughters/name crystal',...
            '/gate/block/daughters/insert box',...
            '/gate/crystal/geometry/setXLength 7.0 mm',...
            '/gate/crystal/geometry/setYLength 1.5 mm',...
            '/gate/crystal/geometry/setZLength 1.5 mm',...
            '/gate/crystal/setMaterial LYSO',...
            '#	R E P E A T    C R Y S T A L',...
            '/gate/crystal/repeaters/insert cubicArray',...
            '/gate/crystal/cubicArray/setRepeatNumberX 1',...
            '/gate/crystal/cubicArray/setRepeatNumberY 20',...
            '/gate/crystal/cubicArray/setRepeatNumberZ 60',...
            '/gate/crystal/cubicArray/setRepeatVector 0. 1.68 1.68 mm',...
            '#	R E P E A T    BLOCK',...
            '/gate/block/repeaters/insert ring',...
            '/gate/block/ring/setRepeatNumber 16',...
            '#     A T T A C H    S Y S T E M ',...
            '/gate/systems/ecat/block/attach block',...
            '/gate/systems/ecat/crystal/attach crystal',...
            '#	A T T A C H    C R Y S T A L  SD',...
            '/gate/crystal/attachCrystalSD');
        fprintf(fid5,'\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s','#PHANTOM',...
            '/gate/world/daughters/name phantom',...
            '/gate/world/daughters/insert cylinder',...
            '/gate/phantom/setMaterial Water',...
            '/gate/phantom/geometry/setRmax 9.6 cm',...
            '/gate/phantom/geometry/setHeight 18. cm',...
            '/gate/phantom/placement/setTranslation 0. 0. 0. cm',...
            '/gate/phantom/attachPhantomSD',...
            '#PHYSICS');
        fprintf(fid5,'\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n%s\n%s\n%s\n','/gate/physics/addProcess PhotoElectric',...
            '/gate/physics/processes/PhotoElectric/setModel StandardModel ',...
            '/gate/physics/addProcess Compton',...
            '/gate/physics/processes/Compton/setModel StandardModel',...
            '/gate/physics/addProcess RayleighScattering',...
            '/gate/physics/processes/RayleighScattering/setModel PenelopeModel',...
            '/gate/physics/addProcess ElectronIonisation',...
            '/gate/physics/processes/ElectronIonisation/setModel StandardModel e-',...
            '/gate/physics/processes/ElectronIonisation/setModel StandardModel e+',...
            '/gate/physics/addProcess Bremsstrahlung',...
            '/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-',...
            '/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+');
        fprintf(fid5,'\n%s\n\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n%s\n%s\n\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n','/gate/physics/addProcess PositronAnnihilation',...
            '/gate/physics/addProcess MultipleScattering e+ ',...
            '/gate/physics/addProcess MultipleScattering e-',...
            '/gate/physics/processList Enabled',...
            '/gate/physics/processList Initialized',...
            '#INITIALIZE',...
            '#=====================================================',...
            '# CUTS',...
            '#=====================================================',...
            '/gate/physics/Gamma/SetCutInRegion      crystal 1.0 cm',...
            '/gate/physics/Electron/SetCutInRegion   crystal 1.0 cm',...
            '/gate/physics/Positron/SetCutInRegion   crystal 1.0 cm',...
            '/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm',...
            '/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm',...
            '/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm',...
            '/gate/physics/SetMaxStepSizeInRegion    phantom 0.01 mm',...
            '/gate/run/initialize',...
            '#ADDER',...
            '/gate/digitizer/Singles/insert adder',...
            '#READOUT',...
            '/gate/digitizer/Singles/insert readout',...
            '/gate/digitizer/Singles/readout/setDepth 1',...
            '#ENERGY BLURRING');
        fprintf(fid5,'\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n%s\n%s\n%s\n%s\n%s\n','/gate/digitizer/Singles/insert blurring',...
            '/gate/digitizer/Singles/blurring/setResolution 0.08 ',...
            '/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV',...
            '#ENERGY WINDOW',...
            '/gate/digitizer/Singles/insert thresholder',...
            '/gate/digitizer/Singles/thresholder/setThreshold 250. keV',...
            '/gate/digitizer/Singles/insert upholder',...
            '/gate/digitizer/Singles/upholder/setUphold 650. keV',...
            '#DEAD TIME',...
            '/gate/digitizer/Singles/insert deadtime',...
            '/gate/digitizer/Singles/deadtime/setDeadTime 1000 ns',...
            '/gate/digitizer/Singles/deadtime/setMode paralysable',...
            '/gate/digitizer/Singles/deadtime/chooseDTVolume block');
        fprintf(fid5,'\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n','#coincidence sorter',...
            '/gate/digitizer/Coincidences/setWindow 10. ns',...
            '/gate/digitizer/name                            delay',...
            '/gate/digitizer/insert                          coincidenceSorter ',...
            '/gate/digitizer/delay/setWindow                 10. ns',...
            '/gate/digitizer/delay/setOffset                 500. ns',...
            '/gate/digitizer/delay/describe',...
            '/gate/digitizer/name finalCoinc',...
            '/gate/digitizer/insert coincidenceChain',...
            '/gate/digitizer/finalCoinc/addInputName delay',...
            '/gate/digitizer/finalCoinc/addInputName Coincidences',...
            '/gate/digitizer/finalCoinc/usePriority true',...
            '/gate/digitizer/finalCoinc/describe',...
            '/gate/random/setEngineName JamesRandom',...
            '/gate/random/setEngineSeed auto',...
            '/gate/random/verbose 1',...
            '#SOURCE',...
            '/gate/source/addSource voxel_brain voxel',...
            '/gate/source/voxel_brain/reader/insert interfile',...
            '/gate/source/voxel_brain/interfileReader/translator/insert range',...
            '/gate/source/voxel_brain/interfileReader/rangeTranslator/readTable activity_range_brain.dat',...
            '/gate/source/voxel_brain/interfileReader/rangeTranslator/describe 1',...
            strcat('/gate/source/voxel_brain/interfileReader/readFile hoffman_',num2str(i),'.h33'),...
            strcat('/gate/source/voxel_brain/setPosition',32,num2str(-Length*3),32,num2str(3*(32-i)),' -90 mm'),...
            '/gate/source/voxel_brain/setType backtoback',...
            '/gate/source/voxel_brain/gps/particle gamma',...
            '/gate/source/voxel_brain/setForcedUnstableFlag true',...
            '/gate/source/voxel_brain/setForcedHalfLife 6586.2 s',...
            '/gate/source/voxel_brain/gps/monoenergy 0.511 MeV',...
            '/gate/source/voxel_brain/gps/confine NULL',...
            '/gate/source/voxel_brain/gps/angtype iso',...
            '/gate/source/voxel_brain/dump 1',...
            '/gate/source/list');
        fprintf(fid5,'\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n','#ROOT OUTPUT',...
            '/gate/output/root/enable',...
            strcat( '/gate/output/root/setFileName hoffman_',num2str(i),'_new'),...
            '/gate/output/root/setRootHitFlag 0',...
            '/gate/output/root/setRootSinglesFlag 0',...
            '/gate/output/root/setRootCoincidencesFlag 1',...
            '#ACQUISITION',...
            '/gate/application/setTimeSlice 100. s',...
            '/gate/application/setTimeStart 0. s',...
            '/gate/application/setTimeStop 100. s',...
            '#START',...
            '/gate/application/startDAQ');
        fclose(fid5);
        fprintf(fid3,'%s\n',strcat('(Gate hoffman_',num2str(i),'.mac & )'));
    end
end
fclose(fid3);